//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Project.rc
//
#define IDOTHER                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROJECT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_FULLSCREEN                  129
#define IDC_DRAGDROP                    139
#define IDD_IMAGESETTINGS               140
#define IDD_PREVIEW                     149
#define IDD_VERSEFINDER                 155
#define IDD_PROJECT_DIALOG_SMALL        156
#define IDD_REGISTER                    170
#define IDD_CHOOSE_FONT                 171
#define IDD_MESSAGEBOX                  174
#define IDB_OFFMONITOR                  175
#define IDB_FILELOAD                    177
#define IDB_FONTSELECT                  178
#define IDB_IMAGE                       179
#define IDB_QBHELP                      180
#define IDB_OFFPROJECTOR                182
#define IDB_SEARCH                      185
#define IDB_INFO                        186
#define IDD_CREATECONTENT               187
#define IDB_MANAGECONTENT               188
#define IDB_ADD                         190
#define IDB_EDIT                        191
#define IDB_DELETE                      192
#define IDD_SAVEASEX                    193
#define IDB_BITMAP1                     194
#define IDB_VIDEO                       194
#define IDB_CAPTURE                     195
#define IDC_PROJECT                     1003
#define IDC_VERSEVIEW                   1004
#define IDC_VERSELIST                   1004
#define IDC_ADDVERSE                    1005
#define IDC_MONITOR                     1006
#define IDC_SHOWHIDEPREVIEW             1007
#define IDC_UPDATE                      1008
#define IDC_REMVERSE                    1009
#define IDC_STATIC_FONT                 1010
#define IDC_SHOWTRANSLATION             1012
#define IDC_LOAD                        1013
#define IDC_SAVE                        1014
#define IDC_FONT                        1015
#define IDC_SHOWPASSAGE                 1016
#define IDC_UPDATEVERSETEXT             1017
#define IDC_REMALLVERSE                 1018
#define IDC_STATIC_PTSIZE               1019
#define IDC_PTSIZE                      1020
#define IDC_TXTCOLOR                    1021
#define IDC_BKGCOLOR                    1022
#define IDC_AUTOSIZEFONT                1023
#define IDC_NEXTVERSE                   1024
#define IDC_DELETEGROUP                 1025
#define IDC_FILEGROUP                   1026
#define IDC_ADDGROUP                    1027
#define IDC_DISPLAYGROUP                1028
#define IDC_MONITORGROUP                1029
#define IDC_VERSELIST2                  1030
#define IDC_SETTINGSLIST                1031
#define IDC_SETTINGSGROUP               1032
#define IDC_ADDNEXTVERSE                1033
#define IDC_CENTERJUSTIFY               1034
#define IDC_STATICBIBLE                 1035
#define IDC_PREVIEW                     1036
#define IDC_BKGIMAGE                    1037
#define IDC_STATIC_ARR                  1038
#define IDC_STATIC_CPY                  1039
#define IDC_MIXAMT                      1040
#define IDC_PREVIEWGROUP                1041
#define IDC_STATIC_QB                   1042
#define IDC_STATIC_MAXPTSIZE            1043
#define IDC_STEPAMT                     1044
#define IDC_BKGON                       1045
#define IDC_MAXPTSIZE                   1046
#define IDC_VERSION                     1047
#define IDC_BKGOFF                      1048
#define IDC_STATIC_QB2                  1049
#define IDC_STATIC_VERSION              1050
#define IDC_FONTSELECT                  1051
#define IDC_BKGVIDEO                    1052
#define IDC_BKGMIX                      1053
#define IDC_QUICKGROUP                  1054
#define IDC_BKGCAPTURE                  1054
#define IDC_MIX                         1055
#define IDC_ADDQUICKVERSE               1056
#define IDC_MANAGECONTENT               1057
#define IDC_STATIC_OFF                  1058
#define IDC_STATIC_FULL                 1059
#define IDC_BKGSOLID                    1060
#define IDC_COLOR                       1061
#define IDC_IMAGE                       1062
#define IDC_STEP                        1063
#define IDC_STATIC_SLOW                 1064
#define IDC_STATIC_FAST                 1065
#define IDC_CHECK1                      1066
#define IDC_TRANSITION                  1067
#define IDC_QBHELP                      1068
#define IDC_VIDEO                       1069
#define IDC_STATICHELP                  1070
#define IDC_CAPTURE                     1070
#define IDC_SEARCH                      1071
#define IDC_COMBO_TRANSLATION           1072
#define IDC_STATIC_MANAGECONTENT        1073
#define IDC_STATIC_TRANSLATION          1074
#define IDC_COMBO_BOOK                  1075
#define IDC_STATIC_BOOK                 1076
#define IDC_COMBO_CHAPTER               1077
#define IDC_STATIC_CHAPTER              1078
#define IDC_EDIT_SEARCHPHRASE           1079
#define IDC_STATIC_SEARCHPHRASE         1080
#define IDC_ADDALL                      1081
#define IDB_SPLASH                      1082
#define IDC_LIST_RESULTS                1083
#define IDB_ONMONITOR                   1084
#define IDC_ADDSELECTED                 1085
#define IDC_EDIT_VERSE                  1086
#define IDB_FILESAVE                    1087
#define IDC_EDIT_VERSEHEADER            1088
#define IDB_ONPROJECTOR                 1089
#define IDC_PREVIEWVERSE                1090
#define IDC_STATIC_RESULTS              1091
#define IDC_STATIC_QUICKBIBLE           1092
#define IDC_TAB                         1093
#define IDC_MODE                        1094
#define IDC_STATIC_EMAIL                1095
#define IDC_STATIC_PREVIEW              1096
#define IDC_STATIC_VERSE                1097
#define IDC_STATIC_WEB                  1098
#define IDC_STATIC_WEBLINK              1099
#define IDC_STATIC_REGISTER             1100
#define IDC_COPY                        1101
#define IDC_STATIC_MANUAL               1102
#define IDC_EDIT_NAME                   1103
#define IDC_EDIT_EMAIL                  1104
#define IDC_EDIT_ORDERNUMBER            1105
#define IDC_STATIC_NAME                 1106
#define IDC_STATIC_EMAILADDRESS         1107
#define IDC_STATIC_ORDERNUMBER          1108
#define IDC_EDIT_ORDERCODE              1109
#define IDC_EDIT_FONT                   1110
#define IDC_STATIC_ORDERCODE            1111
#define IDC_FONTLIST                    1112
#define IDC_SAMPLE                      1113
#define IDC_GROUP_SAMPLE                1114
#define IDC_HORZSB                      1115
#define IDC_VERTSB                      1116
#define IDC_SLIDESETTINGSGROUP          1117
#define IDC_MESSAGEBOX                  1118
#define IDC_QUICK_TRANSLATION           1119
#define IDC_QUICK_BOOK                  1120
#define IDC_QUICK_CHAPTER               1121
#define IDC_QUICK_FROMVERSE             1122
#define IDC_QUICK_TOVERSE               1123
#define IDC_STATIC_QUICK_TRANSLATION    1124
#define IDC_STATIC_QUICK_BOOK           1125
#define IDC_MBIMG                       1126
#define IDC_STATIC_QUICK_CHAPTER        1127
#define IDC_STATIC_QUICK_FROMVERSE      1128
#define IDC_BOOKS                       1129
#define IDC_STATIC_QUICK_TOVERSE        1130
#define IDC_CHAPTERS                    1131
#define IDC_MESSAGETEXT                 1132
#define IDC_VERSES                      1133
#define IDC_VALUE                       1134
#define IDC_ADD_BOOK                    1135
#define IDC_EDIT_BOOK                   1136
#define IDC_DELETE_BOOK                 1137
#define IDC_ADD_CHAPTER                 1138
#define IDC_EDIT_CHAPTER                1139
#define IDC_DELETE_CHAPTER              1140
#define IDC_ADD_VERSE                   1141
#define IDC_STATIC_EDITCONTENT          1142
#define IDC_DELETE_VERSE                1143
#define IDC_EDIT_VERSETEXT              1144
#define IDC_STATIC_EDITVERSETEXT        1145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
